name = "nasa-worker"
main = "index.js"
compatibility_date = "2025-05-01"
compatibility_flags = ["nodejs_compat"]

[[routes]]
pattern = "eyeonthefire.com/api/nasa/*"
zone_name = "eyeonthefire.com"

[observability.logs]
enabled = true