```toml
name = "nasa-worker"
main = "src/index.js"
compatibility_date = "2025-04-30"
compatibility_flags = ["nodejs_compat"]

[[routes]]
pattern = "eyeonthefire.com/api/nasa/*"
zone_name = "eyeonthefire.com"
```