name = "nasa-worker"
main = "index.js"
compatibility_date = "2025-05-01"
compatibility_flags = ["nodejs_compat"]

[[routes]]
pattern = "eyeonthefire.com/api/nasa/*"
zone_name = "eyeonthefire.com"

[observability.logs]
enabled = true

[vars]
NASA_FIRMS_MAP_KEY = "YOUR_MAP_KEY_HERE" # Placeholder; actual value set via `wrangler secret put`