name = "firemap-worker"
main = "src/index.js"
compatibility_date = "2025-05-19"
[[routes]]
pattern = "eyeonthefire.com/*"
[[kv_namespaces]]
binding = "eyeonthefire-keys"
id = "7870aa9dfbfb404aa043612f7cf6a59a"
[observability.logs]
enabled = true
