name: Deploy NASA Worker
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install wrangler@latest
      - name: Navigate to firemap-worker directory
        run: cd firemap-worker
      - name: Validate Wrangler config
        run: npx wrangler deploy --dry-run
        working-directory: firemap-worker
      - name: Deploy to Cloudflare
        run: npx wrangler deploy
        working-directory: firemap-worker
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
